name: Publish Nightly Package

on:
  push:
    branches:
    - master
    paths:
    - 'src/**'

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest]
        dotnet: ['5.0.x']
        configuration: ['Release']

    steps:
    - uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0

    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}

    - name: Build and create nuget packages
      run: dotnet pack -c ${{ matrix.configuration }}

    - name: Publish NuGet Packages to GitHub
      run: dotnet nuget push ./bin/Packages/${{ matrix.configuration }}/Nine.Geometry.*.nupkg --skip-duplicate --no-symbols true -s https://nuget.pkg.github.com/nine/index.json -k ${{ secrets.GITHUB_TOKEN }}

# Skip NuGet
#    - name: Publish NuGet Packages to NuGet
#      run: dotnet nuget push ./bin/Packages/${{ matrix.configuration }}/Nine.Geometry.*.nupkg --skip-duplicate --no-symbols true -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_TOKEN }}
